### ISSUE TITLE
Minimize and compress the standard library

### ISSUE THREAD

**Issue by brechtm** [pybee/Python-Apple-support#13]
The `lib/pythonX.Y` directory can be replaced with `lib/pythonXY.zip`, which drastically reduces the size of the distribution. To further reduce the size needed for the standard library, it's possible to only include the `pyc` files in the zip file.

The size of `lib/python3.5` for a macOS x86_64 distribution:
- as is: 117 MB
- without the test directory: 63 MB
- with only the `opt-2.pyc` files: 23 MB
- zipped: 9.2 MB

It should be possible to reduce this even more, as the `python35.zip` included with [Windows x86-64 embeddable Python 3.5.2 distribution](https://www.python.org/ftp/python/3.5.2/python-3.5.2-embed-amd64.zip) is only 2.2 MB. Perhaps it's possible to use [make_zip.py](https://hg.python.org/cpython/file/812e30f67d6e/Tools/msi/make_zip.py) from the CPython repository that is used to created the Windows embeddable distributions.

**Comment by freakboy3742** [comment]
This *should* be done already - at least, I wrote code to do it. However, I appear to have inadvertently disabled this code before doing the last public release (as reported in #8). I'll close this ticket in preference to that one.
