### ISSUE TITLE
The python executable does not run on older OS X versions

### ISSUE THREAD

**Issue by brechtm** [pybee/Python-Apple-support#16]
Perhaps setting `MACOSX_DEPLOYMENT_TARGET` can help prevent this as suggested in [Creating an embeddable Python distribution on OS X](http://joaoventura.net/blog/2016/embeddable-python-osx-from-src/).

**Comment by brechtm** [comment]
Running Python 3.5.2 built on Sierra on Yosemite:

```
Tests-MacBook-Pro:~ test$ /Applications/rinoh.app/Contents/MacOS/rinoh 
dyld: lazy symbol binding failed: Symbol not found: _getentropy
  Referenced from: /Applications/rinoh.app/Contents/Resources/python/bin/python3 (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _getentropy
  Referenced from: /Applications/rinoh.app/Contents/Resources/python/bin/python3 (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

/Applications/rinoh.app/Contents/MacOS/rinoh: line 5:   611 Trace/BPT trap: 5       python/bin/python3 -m rinoh_macapp.app
```

**Comment by freakboy3742** [comment]
Thanks for the report. I'll take a look at this when I roll the next release of the support packages.

**Comment by freakboy3742** [comment]
If I'm reading this right, the change you've suggested should also result in a build that works on any release back to Mountain Lion. Unfortunately, I don't have a machine available to test this - I'm currently on Yosemite, and don't have easy access to Sierra or any earlier releases. 

Are you able to confirm that adding `MACOSX_DEPLOYMENT_TARGET=10.8` to the configure statement at [line 259 of the Makefile](https://github.com/pybee/Python-Apple-support/blob/3.5/Makefile#L259) results in a macOS build that works on Yosemite?

**Comment by brechtm** [comment]
I installed Yosemite in a VirtualBox VM. That was not without problems, however. VMWare Fusion or Parallels should work better.

You might want to consider setting up CI on Travis to build the macOS binaries. Unfortunately, the macOS build servers are overloaded as is.

**Comment by brechtm** [comment]
Perhaps another option is to build the binaries on an old macOS version, though I'm not sure they will run on later versions. The oldest [macOS version supported by Travis](https://docs.travis-ci.com/user/osx-ci-environment/) is Yosemite (10.10). I would like to support at least back to 10.8. Do you think there is a need to support older versions?

**Comment by brechtm** [comment]
Here's a [.travis.yml](https://github.com/brechtm/Python-Apple-support/blob/3.5-travis/.travis.yml) to build binaries on [Travis](https://travis-ci.org/brechtm/Python-Apple-support). It would be good to add basic tests, or perhaps even run the Python test suite. You could also automatically upload the tar.gz to Bintray, for example.

But since Travis only supports OS X back to Yosemite, the produced binaries won't run on older OS X versions. I don't suppose older SDKs are present on the Travis VM images, so we can't use the `MACOSX_DEPLOYMENT_TARGET` variable.

**Comment by freakboy3742** [comment]
This should be addressed in the most recent binary builds (uploading as I type).

I agree that an automated build & test would be desirable; that should be opened as a separate issue.
