### ISSUE TITLE
Python 3.6

### ISSUE THREAD

**Issue by dimaqq** [pybee/Python-Apple-support#18]
Pretty please :)

**Comment by freakboy3742** [comment]
Absolutely - it's on the list of things to look at (it's just a very long list :-)

**Comment by kersson** [comment]
@freakboy3742 any progress on this? I'm looking into it myself. If you can give me any pointers, I'd greatly appreciate it!

**Comment by freakboy3742** [comment]
@kersson Unfortunately no - I haven't taken a look at it yet. If you want to have a swing at it, you can download the project source files and modify the Makefile to point at Python 3.6 sources... then debug whatever problems emerge. There will almost certainly be some problems with the source code patch (line offset, etc); but there may also be other issues.

**Comment by kersson** [comment]
If I'm able to get things to compile, what's the best way to generate a new `Python.patch` file? For example, did you use `diff` to generate the patch from the extracted sources in the `build` directory? Just want to be able to generate it in the exact same way so I can easily contribute it back.

**Comment by dimaqq** [comment]
I supposed it's time to update openssl as well.

**Comment by kersson** [comment]
WIP: https://github.com/ButterflyNetwork/Python-Apple-support/commits/3.6.0
So far I've got 3.6.0 compiling and have a simple "Hello World" test project working.

**Comment by kersson** [comment]
Bumped to 3.6.1: https://github.com/ButterflyNetwork/Python-Apple-support/commits/3.6.1

**Comment by dimaqq** [comment]
@kersson perhaps you can make a pull request?

P.S. I think `README.rst` ought to be modified to reflect the version too :)

**Comment by kersson** [comment]
Yes, I'd be happy to.  We've been using my build for a while so I think it's good to go.  I'll double-check that there isn't anything that needs to be cleaned up and I'll put out a PR.  Full disclosure, I'm about to go on vacation for a week, so you probably won't see a PR until mid-July.

**Comment by dimaqq** [comment]
Meanwhile, that branch doesn't compile [fully] for me:
```
xcrun --sdk appletvsimulator clang -arch x86_64 --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/SDKs/AppleTVSimulator10.2.sdk -mtvos-version-min=9.0   -I. -Icrypto/include -Iinclude -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSLDIR="\"/Users/dima/Python-Apple-support/build/tvOS/openssl-1.1.0e-appletvsimulator.x86_64\"" -DENGINESDIR="\"/usr/local/lib/engines-1.1\"" -O3 -D_REENTRANT -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/SDKs/../SDKs/AppleTVSimulator10.2.sdk -fno-common  -fPIC -MMD -MF crypto/async/arch/async_null.d.tmp -MT crypto/async/arch/async_null.o -c -o crypto/async/arch/async_null.o crypto/async/arch/async_null.c
In file included from crypto/async/arch/async_null.c:11:
In file included from crypto/async/arch/../async_locl.h:30:
crypto/async/arch/../arch/async_posix.h:45:13: error: 'setcontext' is unavailable: not available on tvOS
            setcontext(&n->fibre);
            ^
/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/SDKs/../SDKs/AppleTVSimulator10.2.sdk/usr/include/ucontext.h:39:6: note:
      'setcontext' has been explicitly marked unavailable here
int  setcontext(const ucontext_t *) __OSX_AVAILABLE_BUT_DEPRECATED(__MAC_10_5, __MAC_10_6, __IPHONE_2_0, __IPHONE_2_0) __WATCHOS_P...
     ^
1 error generated.
```

`iOS` target did get made though :)

**Comment by kersson** [comment]
Ah yes, I haven't tested at all on tvOS.  Sorry, we were super focused on iOS only.  I can take a look at that as well.

**Comment by dimaqq** [comment]
Meanwhile I've posted pre-built versions of the frameworks at https://github.com/dimaqq/Python-Apple-support/releases/tag/3.6.1-b1

That's a direct clone from @kersson 

Some improvement can be seen, as iOS is now down to ~50MB (closer to macOS ~30MB vs 3.5.x ~100MB).

I'll amend this comment and/or release if I find any issues.

**Comment by freakboy3742** [comment]
This should be addressed in the most recent binary builds (uploading as I type). I've also got builds for Python 3.7 ready to go, as soon as there's an official release.
