### ISSUE TITLE
Support IPv6

### ISSUE THREAD

**Issue by grivescorbett** [pybee/Python-Apple-support#2]
I needed IPv6 support for my project, simply changing --disable-ipv6 to --enable-ipv6 worked fine for me.  Perhaps make this the default or configurable?

**Comment by freakboy3742** [comment]
Ah - good to know. Disabling that flag was some cargo-culting from a project that I used to get started; if it works when it's enabled, I'll turn it on for the next release.

**Comment by grivescorbett** [comment]
Awesome.  P.S. this project of yours really, really helped me out :)

**Comment by cfagot** [comment]
Is there any chance you could update the binaries with ipv6 enabled?  ios apps are required to support ipv6 so it isn't a small thing.  I'm currently trying to rebuild myself, but it doesn't build out of the box on OSX 10.11.6 and xcode 8.2.1.

**Comment by freakboy3742** [comment]
@cfagot I've just completed a rebuild of all the support packages with `--enable-ipv6` turned on:
* 3.4-b4
* 3.5-b5
* 3.6-b2
They're uploading now; the links on the branch homepage will be updated as soon as the uploads have completed.

That said: I'd be interested to know what build errors you were getting, so we can fix that problem. If you're able to provide error logs etc, please open a new ticket.

**Comment by cfagot** [comment]
Thanks for updating those.  I noticed, though, that you didn't update the 2.7 branch.  Was that on purpose or an oversight?

In any case, I will definitely open a new ticket with my build logs in the morning.

**Comment by freakboy3742** [comment]
FYI: 3.4, 3.5 and 3.6 builds are now up.

Skipping the 2.7 branch was semi-on purpose. Given that Python 2.7 is slightly over 2 years away from being formally deprecated, and anyone developing code for mobile will be starting a new project, I haven't been putting much effort into 2.7 support.

However, I can just enable the flags on the existing patch and see what happens... I'll run that now and get back to you.

**Comment by freakboy3742** [comment]
Ok - you're in luck :-)

I've just updated the patch for Python 2.7.14, including IPv6 support. Support packages are being uploaded right now.

**Comment by cfagot** [comment]
Oh that's great.  Thanks!  Believe it or not, our product is 10 years old, but just moved to android last year and moving to ios now.

**Comment by freakboy3742** [comment]
My apologies - I uploaded the binaries, but forgot to push the repository changes. They should be there now.

**Comment by cfagot** [comment]
The link actually goes to a NoSuchKey xml file. (I feel like such a pain :).

https://s3-us-west-2.amazonaws.com/pybee-briefcase-support/Python-Apple-support/2.7/iOS/Python-2.7-macOS-support.b3.tar.gz

**Comment by freakboy3742** [comment]
Hey, I'm the one who keeps messing up :-)

I've just fixed them... I hope... :-)
