### ISSUE TITLE
Py_Initialize: can't initialize sys in XCode 8

### ISSUE THREAD

**Issue by chinsyo** [pybee/Python-Apple-support#22]
I just download the latest release for iOS platform, drag into project and run the hello world.
---
xcode output:
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: Py_Initialize: unable to load the file system codec
ImportError: No module named 'encodings'
---
code in ViewController.m:
```objc
#import <Python/Python.h>
- (void)viewDidLoad {
    Py_Initialize();
    PyRun_SimpleString("print(\"Hello world!\")");
    Py_Finalize();
}
```
---
Frameworks:
...
libsqlite.tbz
libz.tbz
---
Enviorment:
XCode 8
iOS 9.3

**Comment by chinsyo** [comment]
I have try ```Py_SetPythonHome()``` with NSHomeDirectory() etc. and it just didn't work. Could you give me some advice or sample code.

thx.

**Comment by dimaqq** [comment]
I don't know for sure what's up, but it may help to cross-check your code with `main.m` that cookiecutter template generates, you can check the result e.g. here https://github.com/dimaqq/playing-with-python-on-ios/blob/master/dimark/main.m

You'll see there's a bunch more settings calls before `Py_Initialize`

**Comment by chinsyo** [comment]
@dimaqq Thanks for your answer. I'll try it.

**Comment by settwi** [comment]
@chinsyo Any luck resolving this? I'm having a very similar issue. App builds and starts, but calling `Py_Initialize` crashes it.

**Comment by AnuiShark** [comment]
Hi there. I have tried the same code in the link above and on Xcode 8.x but Py_Initialize() still results in:

Fatal Python error: Py_Initialize: unable to load the file system codec
ImportError: No module named 'encodings'

```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    
    NSString *tmp_path;
    NSString *python_home;
    wchar_t *wpython_home;
    
    NSString * resourcePath = [[NSBundle mainBundle] resourcePath];
    
    // Special environment to prefer .pyo; also, don't write bytecode
    // because the process will not have write permissions on the device.
    putenv("PYTHONOPTIMIZE=");
    putenv("PYTHONDONTWRITEBYTECODE=1");
    
    python_home = [NSString stringWithFormat:@"%@/Library/Python.framework/Resources", resourcePath, nil];
    NSLog(@"PythonHome is: %@", python_home);
    wpython_home = Py_DecodeLocale([python_home UTF8String], NULL);
    Py_SetPythonHome(wpython_home);
    
    // iOS provides a specific directory for temp files.
    tmp_path = [NSString stringWithFormat:@"TMP=%@/tmp", resourcePath, nil];
    putenv((char *)[tmp_path UTF8String]);
    
    NSLog(@"Initializing Python runtime");
    Py_Initialize();
    PyRun_SimpleString("from time import time,ctime\n"
                       "print('Today is', ctime(time()))\n");
    // Override point for customization after application launch.
    return YES;
}
```

Any help would be appreciated

**Comment by freakboy3742** [comment]
It's very important that you get the right template depending on your Python version. Python 3.4 and 3.5 require very different startup code, and if you try to run a 3.4 template using Python 3.5, you're going to get errors like the one you describe.

**Comment by AnuiShark** [comment]
I was able to make this work by doing the following:

```
    NSString *tmp_path;
    NSString *python_home;
    wchar_t *wpython_home;
    
    NSString * resourcePath = [[NSBundle mainBundle] resourcePath];
    
    // Special environment to prefer .pyo; also, don't write bytecode
    // because the process will not have write permissions on the device.
    putenv("PYTHONOPTIMIZE=");
    putenv("PYTHONDONTWRITEBYTECODE=1");
    
    python_home = [NSString stringWithFormat:@"%@/Python.framework/Resources", resourcePath, nil];
    NSLog(@"PythonHome is: %@", python_home);
    wpython_home = Py_DecodeLocale([python_home UTF8String], NULL);
    Py_SetPythonHome(wpython_home);
    
    // iOS provides a specific directory for temp files.
    tmp_path = [NSString stringWithFormat:@"TMP=%@/tmp", resourcePath, nil];
    putenv((char *)[tmp_path UTF8String]);
    
    NSLog(@"Initializing Python runtime");
    Py_Initialize();
```

And I had to copy the Python.framework as part of build settings 

<img width="748" alt="screen shot 2017-07-23 at 8 39 57 pm" src="https://user-images.githubusercontent.com/1156312/28507361-27ca3476-6fe7-11e7-85a9-8f0ef5fcf2d6.png">

**Comment by freakboy3742** [comment]
Closing on the basis the problem seems to be resolved; please reopen if that's not the case.
