### ISSUE TITLE
Import framework to Swift framework

### ISSUE THREAD

**Issue by anuragajwani** [pybee/Python-Apple-support#25]
Hi,

I am having trouble using the Python 2.7 framework on iOS. I copied the framework into the working directory and then linked it with my own framework. I keep getting "No such module" error when I import Python.

I have a bunch of files written in Python and I'd like to access a function within the file. Is there any tutorial I could follow that would show me how to configure and use this framework correctly?

Thanks,
A

**Comment by dimaqq** [comment]
What do you target, ios or macos?
Also, did you use a cookie-cutter template, or tried to DIY?

P.S. If you want to compare results of your effort to something that happens to work, have a look at https://github.com/dimaqq/playing-with-python-on-ios

**Comment by anuragajwani** [comment]
Thanks for the quick response, my target is and iOS Dynamic Framework. I checked out the cookie-cutter template but that is written in ObjC. I am having trouble on importing it so a Swift Framework. Thanks for the example. Does the Python framework only work to run Python apps? Could it be used as a subsystem in a framework running on another language such as Swift?

**Comment by dimaqq** [comment]
"framework" is applespeak for library. you can use it for whatever you want :) cookiecutter creates a bootstrap that sets a few bits on python interpreter and points it to python code.

You'd have to adapt or refactor https://github.com/dimaqq/playing-with-python-on-ios/blob/master/dimark/main.m to suit the need that you describe.

**Comment by anuragajwani** [comment]
I am trying to follow your example by creating a new static library to wrap the Python code I am trying to run. As a first step I followed the instructions https://github.com/dimaqq/playing-with-python-on-ios and tried running that app but I still get an error from the Python framework not being in the project.

Modified the Header search path to `~/Downloads/Python-3.5-iOS-support.b3/Python.framework/Resources/include/python3.5`

![screen shot 2017-05-09 at 14 24 18](https://cloud.githubusercontent.com/assets/7071488/25853075/639998de-34c3-11e7-8096-23ee1742cff7.png)

Sorry for my lack of knowledge, I think I missing something here.

**Comment by anuragajwani** [comment]
Fiddling with the Header Search path and the User Header Search path I got it working. Still no luck with Swift though so I am embedding the code within another static library that will then be imported to the Swift framework. Thanks for you help :), if successful I will try to contribute with a little blog post with a github repo so others can call Python code within a framework.
