### ISSUE TITLE
Broken Links (3.7.0)

### ISSUE THREAD

**Issue by kaka012** [pybee/Python-Apple-support#30]
The python source is downloaded from [https://www.python.org/ftp/python/3.7.0/Python-3.7.0.tgz](https://www.python.org/ftp/python/3.7.0/Python-3.7.0.tgz). This URL no longer exists, causing tar to fail trying to handle the 404 error page as an archive. The current URL should be [https://www.python.org/ftp/python/3.7.0/Python-3.7.0a3.tgz](https://www.python.org/ftp/python/3.7.0/Python-3.7.0a3.tgz), but the applied patches probably need to be changed as well.
The links for the pre-built versions of the framework in the README are also broken.

**Comment by freakboy3742** [comment]
Python 3.7.0 hasn't been released yet, so we don't yet officially support it. I've just reflected that status n the READMEs
