### ISSUE TITLE
Building frameworks should respect case sensitivity.

### ISSUE THREAD

**Issue by Longhanks** [pybee/Python-Apple-support#32]
When building a project on a case sensitive filesystem, the Xcode linker was unable to find XZ.framework and BZip2.framework on my machine. As it turns out, the Makefile creates fat binaries and symlinks named "xz" and "bzip2", which are usually equal, since Macs per default ship with a case insensitive filesystem. However, choosing a case sensitive filesystem (doesn't matter if HFS+ or APFS) is possible, and the fix is very simple: Create the fat binaries embedded in the framework as well as the symlinks with respect to case sensitivity.

Regarding the pre built packages, it is sufficient to rename the binaries and recreate the symlinks, I was able to successfully link the frameworks after a simple rename.

I will create a pull request demonstrating the fix for the 3.6 branch.

**Comment by freakboy3742** [comment]
Well that's annoying... Thanks for the report!

**Comment by freakboy3742** [comment]
I've merged, #33, so I presume this is fixed; feel free to reopen if it's not.

**Comment by Longhanks** [comment]
Thanks!
