### ISSUE TITLE
Fix python building to include hashlib's c helper function

### ISSUE THREAD

**Issue by cculianu** [pybee/Python-Apple-support#40]
I submitted PR #36 through #39 for this already, but am creating an issue here just for completeness.

The basic idea is hashlib uses a C helper function to query openssl lib for the hash functions provided by it (such as ripemd160).  The 1-line change PR I submitted adds the compilation of the C function to the final built libPython.a, so that hashlib can do its magic and provide all hash functions.

Without it, only a very basic set of hash functions are compiled in to libPython.a's modules.  With it, you get more hash functions.  It's a win/win as far as I can tell. ;)

**Comment by freakboy3742** [comment]
Thanks - the build and release process takes a while, so these should start trickling into new support binaries over the next day or so.

**Comment by freakboy3742** [comment]
I've just finished releasing 3.4-b6, 3.5-b7 and 3.6-b5, integrating the `_hashlib` changes.

**Comment by cculianu** [comment]
That was fast.  👍 

Thank you for providing this great support lib and for briefcase and for everything else!
