### ISSUE TITLE
I cannot work out how to actually get a framework out of this thing

### ISSUE THREAD

**Issue by colons** [pybee/Python-Apple-support#41]
I am probably missing something obvious here, so apologies in advance.

I've run `make iOS` on two different machines, in the `2.7`, `3.5`, and `3.6` branches, and in no case does it result in a `.framework` bundle, or even a `Versions` folder anywhere within the created directories. The output is _extremely_ verbose, but it certainly appears to have exited successfully; it made some folders and an archive, and closed with exit code 0.

When I first ran it and couldn't find a `.framework`, I had assumed that I have to make the bundle myself and copy the built files into it, but there are a couple of projects on GitHub that make no such reference to that being a necessary step, despite claiming to use this project to build their actual `.framework` bundles.

Is there something I'm missing here? How do I actually get a `.framework` out of this thing, or is that not how this is supposed to work and I've misunderstood what you mean by 'Apple Framework format'? If not, is there something about the output I do get that would help work out what might be going on?

**Comment by freakboy3742** [comment]
My apologies - documentation is lagging behind the project. The individual branches have been updated, but the main project landing page hasn't. I'll change this shortly.

The packaging format has recently changed from ".framework" output to produce static libraries. This was the results of rejections from the App Store; Apple's automated tooling rejects static libraries collected in .framework format. 

So - the packaged content now produces a "Support" directory, and a few static .a files.

The best way to see this code in action is to use the [Python iOS template](https://github.com/pybee/Python-iOS-template) - that's a cookiecutter project that will roll out a full Xcode project where the Support folder can be dropped in; or [briefcase](http://github.com/pybee/briefcase), which is tooling to turn a packaged Python project into an distributable app.

**Comment by freakboy3742** [comment]
FYI - I've just updated the main README to reflect the new state of packaging.
