### ISSUE TITLE
import Numpy Compiler Error

### ISSUE THREAD

**Issue by FanKaiyu** [pybee/Python-Apple-support#46]
I try to use PyImport_AppendInittab import PyInit_multiarray.
But Xcode Show Compiler Error

```
Undefined symbols for architecture arm64:
  "_PyInit_multiarray", referenced from:
      _main in main.o
ld: symbol(s) not found for architecture arm64
```

**Comment by freakboy3742** [comment]
Using numpy requires some manual configuration of your project; if you're getting linking errors, it suggests you haven't [followed the instructions](https://github.com/pybee/Python-Apple-support/blob/3.6/patch/numpy/README.rst) for including numpy in your Xcode project.

However, without knowing more details, it's impossible to diagnose any further.

**Comment by FanKaiyu** [comment]
Thanks your help, I had follow the [followed the instructions](https://github.com/pybee/Python-Apple-support/blob/3.6/patch/numpy/README.rst).

This is My Step.

1.Download Python-Apple-support-3.6

2.`make numpy`
   The Build Process outpurt is [here](https://gist.github.com/FanKaiyu/db66064f191dac03ac63146b11b42433), I  also try command with `    make numpy-iOS`, but it's show error.
  
3.Because it's not generate  dist/numpy folder,so I use command
   `make numpy-macOS `
    generate dist/numpy folder and copy it to xcode project
    (by the way. project is gen from Python-iOS-template)

Maybe I need fix the problem at setp 2? Any comments will be much appreciated！
