### ISSUE TITLE
"ld: framework not found Python"

### ISSUE THREAD

**Issue by vihanb** [pybee/Python-Apple-support#48]
So I'm not sure if I'm approaching this the wrong way (probably an issue on my end) but basically I've been able to build the Python framework for iOS. In my app I essentially have a Python library that I'd like to integrate with, that library interacts with some native Obj-C code. So after adding the Python.framework to my project. I setup the Framework Search Path to point to `$(PROJECT_DIR)/MyApp/Support` which is the directory that contains the Python.framework. I've also added it as a Linked Framework/Embedded Binary however once I build my project I get `ld: framework not found Python` when it attempts to link to the framework, which is unusual because the framework exists in that directory.

**Comment by freakboy3742** [comment]
It's difficult to diagnose without having access to your full project; but if you want a reference Xcode project, [Python-iOS-template](https://github.com/pybee/Python-iOS-template) is a cookiecutter project that will generate one for you. There are a couple of build configuration items that need to be in place for the build to succeed.

**Comment by vihanb** [comment]
Found what I was looking for there, thanks :)
