### ISSUE TITLE
dynlibs missing from Python-3.5-macOS-support.b2.tar.gz (and others?)

### ISSUE THREAD

**Issue by brechtm** [pybee/Python-Apple-support#5]
```
import zlib
```

fails because zlib.cpython-35-darwin.so is not included in Python-3.5-macOS-support.b2.tar.gz.

I first reported this issue at pybee/briefcase#20, but this seems to be a better place to report this.

**Comment by freakboy3742** [comment]
Huh... thanks for the report. I clearly need to do another build. I'll see if I can find time in the next day or two.

**Comment by brechtm** [comment]
The full list of missing dynload libs:

- dbm
- _hashlib
- _sqlite3
- _ssl
- _tkinter
- nis
_ zlib

**Comment by freakboy3742** [comment]
Some of those libraries (_tkinter) are intentionally not included; but others (_ssl) should be there. 

The previous builds had a couple of problems; can you confirm if this is still a problem with the new builds (3.5-b3)?

**Comment by brechtm** [comment]
Comparing the `lib-dynload` folder with that of a pyenv-built CPython 3.5.2 shows thats the list of missing libs is now reduced to:

- _hashlib
- _ssl

**Comment by freakboy3742** [comment]
This should be addressed in the most recent binary builds (uploading as I type).
