### ISSUE TITLE
How can I get python function output (returned values) in iOS app?

### ISSUE THREAD

**Issue by chaocharleswang** [pybee/Python-Apple-support#57]
How can I get python function output (returned values) in iOS app?

**Comment by freakboy3742** [comment]
It's not entirely clear what you're asking. 

If you're asking about invoking Python code from the Objective C stub, then you're using CPython's [embedding API](https://docs.python.org/3/extending/index.html). 

If you're looking for a bridge between Objective C and Python code, then [Rubicon](https://github.com/pybee/rubicon-objc) is the library you're looking for.
