### ISSUE TITLE
iPhone7 support

### ISSUE THREAD

**Issue by appsird** [pybee/Python-Apple-support#7]
Will there be iPhone7 support on the near horizon?

**Comment by freakboy3742** [comment]
Are you actually getting an error with iPhone 7, or is this just a case of the homepage not listing iPhone 7 explicitly? I'm not aware of any specific updates that should be required, but I also don't have an iPhone 7 for testing purposes.

**Comment by appsird** [comment]
This is just because of your home page.

**Comment by freakboy3742** [comment]
I've just updated the homepage to reflect the fact that iPhone7 should be supported.
